### PR TITLE
Uprev for Chrome OS input tools

### PR DESCRIPTION
**Pull request by rsadam-google**
@wnwen-google please take a look!

### CODE REVIEW

**Comment by wnwen-google** [comment]
I don't get new notifications unless you make a new comment. Please make a new comment when PRs are updated. :)

Assuming you'll incorporate the script deletions in this CL too?

**Comment by rsadam-google** [comment]
I didn't realize that! Will do in future.

Yeah I'm waiting for your make.sh change to land and I'll do the deletion as the third commit.

**Comment by wnwen-google** [comment]
Landed make.sh change.

**Comment by rsadam-google** [comment]
Deleted the unused files. PTANL!

**Comment by wnwen-google** [comment]
lgtm. Remember to remove the deleted files on Chromium side. Thanks. :)

**Pull request merged**
