### PR TITLE
mohdmurad

### PR DESCRIPTION
**Pull request by mrmurad99**
murad@ranacomarine.com

### CODE REVIEW

**Comment by mrmurad99** [comment]
signed it!

mrmurad99

**Comment by jscot33** [comment]
Signed CLA

**Comment by ppghijk** [comment]
Are you talking me?

**Comment by ppghijk** [comment]
I don't know what I do. Now I can't upgrade my firmware.

**Comment by ppghijk** [comment]
Oh,  my God. Awesome I Don't understand.  I am simple user.

**Comment by lotem** [comment]
This doesn't look like a change related to the project.

**Pull request closed without merging**
